### ISSUE TITLE
ChatBox

### ISSUE THREAD

**Issue by aalsaedi265** [learn-co-curriculum/phase-0-css-graffiti-lab#7]
### Canvas Link

https://learning.flatironschool.com/courses/5461/assignments/164051?module_item_id=353297

### Concern

Hello for this whole module the ChatBox to the right of the FlatIron canvas has been absent I do not use if this is intentional or there is a bug, It was present yesterday when I was on the module before it, then this and it disappeared.

**Comment by ihollander** [comment]
Hi @aalsaedi265 - thanks for flagging this. I've raised this issue to our Canvas support team and will let you know when I head back!

**Comment by ihollander** [comment]
The Canvas support team fixed this over the weekend and I was able to verify that the chat box is available in your Canvas prework course now, so I'll close this issue. Happy coding!
